apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  RABBIT_USER: {{ .Values.RABBIT_USER | b64enc }}
  RABBIT_PASSWORD: {{ .Values.RABBIT_PASSWORD | b64enc }}
  COUCHDB_LOGIN: {{ .Values.COUCHDB_LOGIN | b64enc }}
  COUCHDB_PASSWORD: {{ .Values.COUCHDB_PASSWORD | b64enc }}
